title = "IPASC"
baseURL = "https://www.example.com"
#baseURL = "http://www.jgroehl.com/ipasc/test/airspace/"
languageCode = "en-us"
theme = "airspace"

[menu]
  [[menu.header]]
    weight = 2
    name = "Consortium"
    url = "/consortium"
  [[menu.header]]
    weight = 2
    name = "Get Involved"
    url = "/getinvolved"
#  [[menu.header]]
#    weight = 2
#    name = "Publications"
#    url = "/publications"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.wrapper]
    enable = true
    title = "Mission Statement"
    italic = "Goals of the International Photoacoustic Standardisation Consortium (IPASC)"

  [params.feature]
    enable = true
    title = "Comparability of clinical photoacoustic imaging systems"
    content = "As a growing number of research groups exploit photoacoustic imaging (PAI), there is an increasing need to establish common standards for photoacoustic data and images in order to facilitate open access, use, and exchange of data between different groups. Our aim is to provide a platform that enables reserach groups and companies from all over the world to test their developed photoacoustic imaging modalities."
    [params.feature.button]
      caption = "Get Involved"
      url = "/getinvolved"
	  
  [params.main]
    enable = true
    title = "International Photoacoustic Standardisation Consortium"
    subtitle = " "
    paragraph = " "

  [params.call]
    enable = true
    title = " "
    paragraph = " "
	
  [params.consortium]
    enable = true
    title = "Consortium Members"
    subtitle = "Listing of all members of the consortium"
	
  [params.imprint]
    enable = true
    title = "Imprint"
    subtitle = ""
	
  [params.dpp]
    enable = true
    title = "Data Protection Policy"
    subtitle = ""
	
  [params.publications]
    enable = true
    title = "Publications"
    subtitle = "An overview over all IPASC publications"

  [params.contact]
    enable = false
