title = "IPASC"
#baseURL = "http://www.ipasc.science/"
baseURL = "http://www.ipasc-test.magix.net/test/"
languageCode = "en-us"

[menu]
  [[menu.header]]
    weight = 2
    name = "Consortium"
    url = "/consortium"
  [[menu.header]]
    weight = 2
    name = "Get Involved"
    url = "/getinvolved"
  [[menu.header]]
    weight = 2
    name = "Publications"
    url = "/publications"
  #[[menu.header]]
  #  weight = 2
  #  name = "Themes"
  #  url = "/themes"

# The site's parameters
[params]

  dateFormat = "6 January 2006"

  home = "Home"

  [params.wrapper]
    enable = true
    title = "Mission Statement"
    italic = "Goals of the International Photoacoustic Standardisation Consortium (IPASC)"
 
  [params.main]
    enable = true
    title = "International Photoacoustic Standardisation Consortium"
    subtitle = " "
    paragraph = " "

  [params.call]
    enable = true
    title = " "
    paragraph = " "
	
  [params.consortium]
    enable = true
    title = "Consortium Members"
    subtitle = "Listing of all members of the consortium"
	
  [params.imprint]
    enable = true
    title = "Imprint"
    subtitle = ""
	
  [params.dpp]
    enable = true
    title = "Data Protection Policy"
    subtitle = ""
	
  [params.publications]
    enable = true
    title = "Publications"
    subtitle = "An overview over all IPASC publications"

  [params.contact]
    enable = false
